### ISSUE TITLE
Framework Errors

### ISSUE THREAD

**Issue by ckizer** [lucasnewman/f5-tts-mlx#3]
`python3 -m f5_tts_mlx.generate \
--text "The quick brown fox jumped over the lazy dog." \
--duration 3.5
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/f5_tts_mlx/generate.py", line 13, in <module>
    from vocos_mlx import Vocos
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/vocos_mlx/__init__.py", line 2, in <module>
    from vocos_mlx.model import Vocos
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/vocos_mlx/model.py", line 16, in <module>
    from vocos_mlx.encodec import EncodecModel
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/vocos_mlx/encodec.py", line 57, in <module>
    _lstm_kernel = mx.fast.metal_kernel(
                   ^^^^^^^^^^^^^^^^^^^^^
TypeError: __init__(): incompatible function arguments. The following argument types are supported:
    1. __init__(self, name: str, source: str, header: str = '', ensure_row_contiguous: bool = True, atomic_outputs: bool = False) -> None

Invoked with types: mlx.core.fast.metal_kernel, kwargs = { name: str, input_names: list, output_names: list, header: str, source: str }
ck@StarlinkPro E2-F5-TTS-AI % 
`

**Comment by lucasnewman** [comment]
Try `pip install -U mlx` and see if that helps.

**Comment by mobile-appz** [comment]
> Try `pip install -U mlx` and see if that helps.

I was getting a separate framework error and updating to latest MLX version fixed it, so it might be worth adding this to instructions
