### ISSUE TITLE
Issue running inference using generate.py

### ISSUE THREAD

**Issue by Aalisha** [lucasnewman/f5-tts-mlx#4]
I tried to run the below command - `python f5-tts-mlx/f5_tts_mlx/generate.py --text "<text>" --duration 10 --model  "lucasnewman/f5-tts-mlx" --ref-audio "test.wav" --ref-text "<ref-text>"`

But it is throwing an error regarding invalid padding size -
```
Fetching 2 files: 100% 2/2 [00:00<00:00, 22133.53it/s]
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 1.393 seconds.
Prefix dict has been built successfully.
Generating 2784 total frames of audio...
Fetching 2 files: 100% 2/2 [00:00<00:00, 20661.60it/s]
Traceback (most recent call last):
  File "/content/f5-tts-mlx/f5_tts_mlx/generate.py", line 147, in <module>
    generate(
  File "/content/f5-tts-mlx/f5_tts_mlx/generate.py", line 67, in generate
    wave, _ = f5tts.sample(
  File "/usr/local/lib/python3.10/dist-packages/f5_tts_mlx/cfm.py", line 370, in sample
    cond = mx.pad(cond, [(0, 0), (0, max_duration - cond_seq_len), (0, 0)])
ValueError: Invalid high padding size (-468685) passed to pad for axis 1. Padding sizes must be non-negative

```

**Comment by lucasnewman** [comment]
Try a shorter reference audio, ideally 3-7 seconds.

**Comment by Aalisha** [comment]
Hi, Thank you for your prompt response. I think there were two other issues - I was using CPU and didn't use 24KHZ ref audio in addition to what you mentioned about shorter reference audio. 

After making the changes, still receiving the below error -

```
Fetching 2 files: 100% 2/2 [00:00<00:00, 33026.02it/s]
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.638 seconds.
Prefix dict has been built successfully.
Generating 1198 total frames of audio...
Fetching 2 files: 100% 2/2 [00:00<00:00, 5197.40it/s]
In file included from /root/project/mlx/backend/common/compiled_preamble.h:7:
/root/project/mlx/types/complex.h:14:11: error: ‘is_same_v’ is not a member of ‘std’; did you mean ‘is_same’?
/root/project/mlx/types/complex.h:14:22: error: expected primary-expression before ‘,’ token
/root/project/mlx/types/complex.h:14:20: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
/root/project/mlx/types/complex.h:32:11: error: ‘is_same_v’ is not a member of ‘std’; did you mean ‘is_same’?
/root/project/mlx/types/complex.h:32:22: error: expected primary-expression before ‘,’ token
/root/project/mlx/types/complex.h:32:20: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
In file included from /root/project/mlx/backend/common/compiled_preamble.h:7:
/root/project/mlx/types/complex.h: In function ‘mlx::core::complex64_t mlx::core::operator+(mlx::core::float16_t, const mlx::core::complex64_t&)’:
/root/project/mlx/types/complex.h:109:1583: error: no matching function for call to ‘mlx::core::complex64_t::complex64_t(mlx::core::float16_t&)’
In file included from /root/project/mlx/backend/common/compiled_preamble.h:7:
/root/project/mlx/types/complex.h:41:3: note: candidate: ‘template<class T, class> mlx::core::complex64_t::complex64_t(T)’
/root/project/mlx/types/complex.h:41:3: note:   template argument deduction/substitution failed:
/root/project/mlx/types/complex.h:36:3: note: candidate: ‘mlx::core::complex64_t::complex64_t(std::complex<float>)’
/root/project/mlx/types/complex.h:36:35: note:   no known conversion for argument 1 from ‘mlx::core::float16_t’ {aka ‘mlx::core::_MLX_Float16’} to ‘std::complex<float>’
/root/project/mlx/types/complex.h:35:3: note: candidate: ‘mlx::core::complex64_t::complex64_t(float, float)’
/root/project/mlx/types/complex.h:35:3: note:   candidate expects 2 arguments, 1 provided
/root/project/mlx/types/complex.h:34:8: note: candidate: ‘constexpr mlx::core::complex64_t::complex64_t(const mlx::core::complex64_t&)’
/root/project/mlx/types/complex.h:34:8: note:   no known conversion for argument 1 from ‘mlx::core::float16_t’ {aka ‘mlx::core::_MLX_Float16’} to ‘const mlx::core::complex64_t&’
/root/project/mlx/types/complex.h:34:8: note: candidate: ‘constexpr mlx::core::complex64_t::complex64_t(mlx::core::complex64_t&&)’
/root/project/mlx/types/complex.h:34:8: note:   no known conversion for argument 1 from ‘mlx::core::float16_t’ {aka ‘mlx::core::_MLX_Float16’} to ‘mlx::core::complex64_t&&’
In file included from /root/project/mlx/backend/common/compiled_preamble.h:7:
/root/project/mlx/types/complex.h: In function ‘mlx::core::complex64_t mlx::core::operator+(const mlx::core::complex64_t&, mlx::core::float16_t)’:
/root/project/mlx/types/complex.h:109:1695: error: no matching function for call to ‘mlx::core::complex64_t::complex64_t(mlx::core::float16_t&)’
In file included from /root/project/mlx/backend/common/compiled_preamble.h:7:
/root/project/mlx/types/complex.h:41:3: note: candidate: ‘template<class T, class> mlx::core::complex64_t::complex64_t(T)’
/root/project/mlx/types/complex.h:41:3: note:   template argument deduction/substitution failed:
/root/project/mlx/types/complex.h:36:3: note: candidate: ‘mlx::core::complex64_t::complex64_t(std::complex<float>)’
/root/project/mlx/types/complex.h:36:35: note:   no known conversion for argument 1 from ‘mlx::core::float16_t’ {aka ‘mlx::core::_MLX_Float16’} to ‘std::complex<float>’
/root/project/mlx/types/complex.h:35:3: note: candidate: ‘mlx::core::complex64_t::complex64_t(float, float)’
/root/project/mlx/types/complex.h:35:3: note:   candidate expects 2 arguments, 1 provided
/root/project/mlx/types/complex.h:34:8: note: candidate: ‘constexpr mlx::core::complex64_t::complex64_t(const mlx::core::complex64_t&)’
/root/project/mlx/types/complex.h:34:8: note:   no known conversion for argument 1 from ‘mlx::core::float16_t’ {aka ‘mlx::core::_MLX_Float16’} to ‘const mlx::core::complex64_t&’
/root/project/mlx/types/complex.h:34:8: note: candidate: ‘constexpr mlx::core::complex64_t::complex64_t(mlx::core::complex64_t&&)’
/root/project/mlx/types/complex.h:34:8: note:   no known conversion for argument 1 from ‘mlx::core::float16_t’ {aka ‘mlx::core::_MLX_Float16’} to ‘mlx::core::complex64_t&&’
In file included from /root/project/mlx/backend/common/compiled_preamble.h:7:
/root/project/mlx/types/complex.h: In function ‘mlx::core::complex64_t mlx::core::operator+(mlx::core::bfloat16_t, const mlx::core::complex64_t&)’:
/root/project/mlx/types/complex.h:109:1800: error: no matching function for call to ‘mlx::core::complex64_t::complex64_t(mlx::core::bfloat16_t&)’
In file included from /root/project/mlx/backend/common/compiled_preamble.h:7:
/root/project/mlx/types/complex.h:41:3: note: candidate: ‘template<class T, class> mlx::core::complex64_t::complex64_t(T)’
/root/project/mlx/types/complex.h:41:3: note:   template argument deduction/substitution failed:
/root/project/mlx/types/complex.h:36:3: note: candidate: ‘mlx::core::complex64_t::complex64_t(std::complex<float>)’
/root/project/mlx/types/complex.h:36:35: note:   no known conversion for argument 1 from ‘mlx::core::bfloat16_t’ {aka ‘mlx::core::_MLX_BFloat16’} to ‘std::complex<float>’
/root/project/mlx/types/complex.h:35:3: note: candidate: ‘mlx::core::complex64_t::complex64_t(float, float)’
/root/project/mlx/types/complex.h:35:3: note:   candidate expects 2 arguments, 1 provided
/root/project/mlx/types/complex.h:34:8: note: candidate: ‘constexpr mlx::core::complex64_t::complex64_t(const mlx::core::complex64_t&)’
/root/project/mlx/types/complex.h:34:8: note:   no known conversion for argument 1 from ‘mlx::core::bfloat16_t’ {aka ‘mlx::core::_MLX_BFloat16’} to ‘const mlx::core::complex64_t&’
/root/project/mlx/types/complex.h:34:8: note: candidate: ‘constexpr mlx::core::complex64_t::complex64_t(mlx::core::complex64_t&&)’
/root/project/mlx/types/complex.h:34:8: note:   no known conversion for argument 1 from ‘mlx::core::bfloat16_t’ {aka ‘mlx::core::_MLX_BFloat16’} to ‘mlx::core::complex64_t&&’
In file included from /root/project/mlx/backend/common/compiled_preamble.h:7:
/root/project/mlx/types/complex.h: In function ‘mlx::core::complex64_t mlx::core::operator+(const mlx::core::complex64_t&, mlx::core::bfloat16_t)’:
/root/project/mlx/types/complex.h:109:1913: error: no matching function for call to ‘mlx::core::complex64_t::complex64_t(mlx::core::bfloat16_t&)’
In file included from /root/project/mlx/backend/common/compiled_preamble.h:7:
/root/project/mlx/types/complex.h:41:3: note: candidate: ‘template<class T, class> mlx::core::complex64_t::complex64_t(T)’
/root/project/mlx/types/complex.h:41:3: note:   template argument deduction/substitution failed:
/root/project/mlx/types/complex.h:36:3: note: candidate: ‘mlx::core::complex64_t::complex64_t(std::complex<float>)’
/root/project/mlx/types/complex.h:36:35: note:   no known conversion for argument 1 from ‘mlx::core::bfloat16_t’ {aka ‘mlx::core::_MLX_BFloat16’} to ‘std::complex<float>’
/root/project/mlx/types/complex.h:35:3: note: candidate: ‘mlx::core::complex64_t::complex64_t(float, float)’
/root/project/mlx/types/complex.h:35:3: note:   candidate expects 2 arguments, 1 provided
/root/project/mlx/types/complex.h:34:8: note: candidate: ‘constexpr mlx::core::complex64_t::complex64_t(const mlx::core::complex64_t&)’
/root/project/mlx/types/complex.h:34:8: note:   no known conversion for argument 1 from ‘mlx::core::bfloat16_t’ {aka ‘mlx::core::_MLX_BFloat16’} to ‘const mlx::core::complex64_t&’
/root/project/mlx/types/complex.h:34:8: note: candidate: ‘constexpr mlx::core::complex64_t::complex64_t(mlx::core::complex64_t&&)’
/root/project/mlx/types/complex.h:34:8: note:   no known conversion for argument 1 from ‘mlx::core::bfloat16_t’ {aka ‘mlx::core::_MLX_BFloat16’} to ‘mlx::core::complex64_t&&’
In file included from /root/project/mlx/backend/common/compiled_preamble.h:8:
/root/project/mlx/backend/common/ops.h: At global scope:
/root/project/mlx/backend/common/ops.h:447:25: error: ‘is_integral_v’ is not a member of ‘std’; did you mean ‘is_integral’?
/root/project/mlx/backend/common/ops.h:447:40: error: template argument 1 is invalid
/root/project/mlx/backend/common/ops.h:447:44: error: expected unqualified-id before ‘!’ token
/root/project/mlx/backend/common/ops.h:454:25: error: ‘is_integral_v’ is not a member of ‘std’; did you mean ‘is_integral’?
/root/project/mlx/backend/common/ops.h:454:40: error: template argument 1 is invalid
/root/project/mlx/backend/common/ops.h:454:60: error: expected initializer before ‘<’ token
/root/project/mlx/backend/common/ops.h:464:26: error: ‘is_integral_v’ is not a member of ‘std’; did you mean ‘is_integral’?
/root/project/mlx/backend/common/ops.h:464:39: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
/root/project/mlx/backend/common/ops.h:464:41: error: template argument 1 is invalid
/root/project/mlx/backend/common/ops.h:464:42: error: expected unqualified-id before ‘,’ token
/root/project/mlx/backend/common/ops.h:523:25: error: ‘is_integral_v’ is not a member of ‘std’; did you mean ‘is_integral’?
/root/project/mlx/backend/common/ops.h:523:40: error: template argument 1 is invalid
/root/project/mlx/backend/common/ops.h:523:41: error: expected unqualified-id before ‘,’ token
/root/project/mlx/backend/common/ops.h:528:26: error: ‘is_integral_v’ is not a member of ‘std’; did you mean ‘is_integral’?
/root/project/mlx/backend/common/ops.h:528:39: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
/root/project/mlx/backend/common/ops.h:528:41: error: template argument 1 is invalid
/root/project/mlx/backend/common/ops.h:528:42: error: expected unqualified-id before ‘,’ token
/root/project/mlx/backend/common/ops.h:538:25: error: ‘is_integral_v’ is not a member of ‘std’; did you mean ‘is_integral’?
/root/project/mlx/backend/common/ops.h:538:40: error: template argument 1 is invalid
/root/project/mlx/backend/common/ops.h:538:41: error: expected unqualified-id before ‘,’ token
/root/project/mlx/backend/common/ops.h:543:26: error: ‘is_integral_v’ is not a member of ‘std’; did you mean ‘is_integral’?
/root/project/mlx/backend/common/ops.h:543:39: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
/root/project/mlx/backend/common/ops.h:543:41: error: template argument 1 is invalid
/root/project/mlx/backend/common/ops.h:543:42: error: expected unqualified-id before ‘,’ token
/root/project/mlx/backend/common/ops.h:580:26: error: ‘is_integral_v’ is not a member of ‘std’; did you mean ‘is_integral’?
/root/project/mlx/backend/common/ops.h:580:39: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
/root/project/mlx/backend/common/ops.h:580:41: error: template argument 1 is invalid
/root/project/mlx/backend/common/ops.h:580:42: error: expected unqualified-id before ‘,’ token
/root/project/mlx/backend/common/ops.h:585:25: error: ‘is_integral_v’ is not a member of ‘std’; did you mean ‘is_integral’?
/root/project/mlx/backend/common/ops.h:585:40: error: template argument 1 is invalid
/root/project/mlx/backend/common/ops.h:585:41: error: expected unqualified-id before ‘,’ token
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Compile::eval_cpu] Failed to compile function Ef4BroadcastBFf4DivideAEGf4ErfFHf4BroadcastCIf4AddGHJf4MultiplyAIKf4BroadcastDLf4DivideJK_VCCC_f4_17189564909660296092_contiguous with error code 256.
```

**Comment by lucasnewman** [comment]
Are you running on Apple Silicon? If not, I'm not sure it will work well on the cpu. Otherwise, you might try updating mlx with `pip install -U mlx`

**Comment by Aalisha** [comment]
Thank you for checking! I was running on T4 GPU using Google colab. Thanks! :)
