### ISSUE TITLE
Error when running on my Mac Silicon

### ISSUE THREAD

**Issue by notnotrishi** [lucasnewman/f5-tts-mlx#8]
I'm getting the following error when i try to run it on My Mac Air M2

did a pip install as per readme and ran the following:

python3 -m f5_tts_mlx.generate --text "Hello world"
--
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/f5_tts_mlx/generate.py", line 14, in <module>
    from vocos_mlx import Vocos
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/vocos_mlx/__init__.py", line 2, in <module>
    from vocos_mlx.model import Vocos
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/vocos_mlx/model.py", line 15, in <module>
    from vocos_mlx.encodec import EncodecModel
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/vocos_mlx/encodec.py", line 57, in <module>
    _lstm_kernel = mx.fast.metal_kernel(
                   ^^^^^^^^^^^^^^^^^^^^^
TypeError: __init__(): incompatible function arguments. The following argument types are supported:
    1. __init__(self, name: str, source: str, ensure_row_contiguous: bool = True, atomic_outputs: bool = False) -> None

Invoked with types: mlx.core.fast.metal_kernel, kwargs = { name: str, input_names: list, output_names: list, header: str, source: str }

**Comment by lucasnewman** [comment]
Try `pip install -U mlx`
